### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by phahulin** [poanetwork/poa-popa#155]
- **What is it?** (leave one option)
    * `(Bug)` report (i.e. something doesn't work as it should)

```
Launched testrpc on port 8555
Running: ../node_modules/.bin/truffle test --network coverage
(this can take a few seconds)...
Using network 'coverage'.
Error: Error: base fee exceeds gas limit
    at runCall (/home/travis/build/poanetwork/poa-popa/blockchain/node_modules/ethereumjs-testrpc-sc/build/cli.node.js:71005:17)
    at /home/travis/build/poanetwork/poa-popa/blockchain/node_modules/ethereumjs-testrpc-sc/build/cli.node.js:12656:24
    at replenish (/home/travis/build/poanetwork/poa-popa/blockchain/node_modules/ethereumjs-testrpc-sc/build/cli.node.js:9788:17)
    at iterateeCallback (/home/travis/build/poanetwork/poa-popa/blockchain/node_modules/ethereumjs-testrpc-sc/build/cli.node.js:9773:17)
    at /home/travis/build/poanetwork/poa-popa/blockchain/node_modules/ethereumjs-testrpc-sc/build/cli.node.js:9748:16
    at /home/travis/build/poanetwork/poa-popa/blockchain/node_modules/ethereumjs-testrpc-sc/build/cli.node.js:12661:13
    at /home/travis/build/poanetwork/poa-popa/blockchain/node_modules/ethereumjs-testrpc-sc/build/cli.node.js:67133:16
    at replenish (/home/travis/build/poanetwork/poa-popa/blockchain/node_modules/ethereumjs-testrpc-sc/build/cli.node.js:67080:25)
    at /home/travis/build/poanetwork/poa-popa/blockchain/node_modules/ethereumjs-testrpc-sc/build/cli.node.js:67089:9
    at eachLimit (/home/travis/build/poanetwork/poa-popa/blockchain/node_modules/ethereumjs-testrpc-sc/build/cli.node.js:67013:36)
    at Object.InvalidResponse (/home/travis/build/poanetwork/poa-popa/blockchain/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /home/travis/build/poanetwork/poa-popa/blockchain/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /home/travis/build/poanetwork/poa-popa/blockchain/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /home/travis/build/poanetwork/poa-popa/blockchain/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/home/travis/build/poanetwork/poa-popa/blockchain/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/travis/build/poanetwork/poa-popa/blockchain/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/home/travis/build/poanetwork/poa-popa/blockchain/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/home/travis/build/poanetwork/poa-popa/blockchain/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/home/travis/build/poanetwork/poa-popa/blockchain/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at emitNone (events.js:111:20)
Cleaning up...
Event trace could not be read.
Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...
```

**Comment by fvictorio** [comment]
Fixed in #154.
